### PR TITLE
Fixes URL to docs

### PR DESCRIPTION
**Pull request by dkastl**
Changes proposed in this pull request:
- URL to documentation

### CODE REVIEW

**Review by krashish8 — APPROVED** [review]
Thanks!

**Comment by dkastl** [comment]
I get lots of failing checks. Is this intentional?
Otherwise actions can be also turned off in the Github UI.

**Comment by krashish8** [comment]
Seems that there is some issue with postgres installation:
```
fatal error: postgres.h: No such file or directory
   29 | #include <postgres.h>
      |          ^~~~~~~~~~~~
```
The last run on vrprouting used `postgresql-13`, and now it is using `postgresql-14`. Just guessing, maybe some small fix is needed in the actions. The latest version of PostgreSQL works fine on pgRouting, however.

Obviously, this is not because of your change, so there is no issue in merging, except that it will show a cross in the commit history. I'm a bit busy today, will check this error later today or tomorrow.

**Comment by dkastl** [comment]
I see. No problem. Maybe some dependency has changed something again.

**Pull request merged**
